name: install spaces
author: Tyler Gilbert
description: Prebuilt binaries of https://github.com/work-spaces/spaces
branding:
  icon: activity
  color: purple

runs:
  using: composite
  steps:
    - id: configure
      run: |
        echo platform=${{runner.os == 'macOS' && 'macos-x86_64' || runner.os == 'Windows' && 'windows-x86_64' || 'linux-x86_64'}} >> $GITHUB_OUTPUT
        echo version=spaces-v0.2.0 >> $GITHUB_OUTPUT
        echo working_path=${{runner.temp}}/install-spaces >> $GITHUB_OUTPUT
      shell: bash

    - run: mkdir -p "${{steps.configure.outputs.working_path}}/bin"
      shell: bash

    - run: echo "working_path=${{steps.configure.outputs.working_path}}"
      shell: bash
    
    - run: echo $(ls ${{steps.configure.outputs.working_path}})
      shell: bash

    - run: |
        curl https://github.com/work-spaces/workflows/releases/download/${{steps.configure.outputs.version}}/${{steps.configure.outputs.version}}-${{steps.configure.outputs.platform}}.zip \
        --header "authorization: Bearer ${{ github.token }}" \
        --location --silent --show-error --fail --retry 5 > "${{steps.configure.outputs.working_path}}/spaces.zip"
      shell: bash

    - run: unzip "${{steps.configure.outputs.working_path}}/spaces.zip" -d "${{steps.configure.outputs.working_path}}/bin"
      shell: bash

    - run: echo "bin: ${{steps.configure.outputs.working_path}}/bin"
      shell: bash

    - run: echo "${{steps.configure.outputs.working_path}}/bin" >> $GITHUB_PATH
      shell: bash

    - run: spaces --version
      shell: bash