name: install spaces
author: Tyler Gilbert
description: Prebuilt binaries of https://github.com/work-spaces/spaces
branding:
  icon: activity
  color: purple

runs:
  using: composite
  steps:
    - id: configure
      run: |
        echo platform=${{runner.os == 'macOS' && 'macos-x86_64' || runner.os == 'Windows' && 'windows-x86_64' || 'linux-x86_64'}} >> $GITHUB_OUTPUT
        echo version=spaces-v0.2.0 >> $GITHUB_OUTPUT
        echo working_path=${{runner.temp}}/install-spaces >> $GITHUB_OUTPUT
        echo suffix=zip >> $GITHUB_OUTPUT
      shell: bash

    - run: mkdir -p "${{steps.configure.outputs.working_path}}/bin"
      shell: bash

    - run: |
        curl https://github.com/work-spaces/workflows/releases/download/${{steps.configure.outputs.version}}/${{steps.configure.outputs.version}}-${{steps.configure.outputs.platform}}.${{steps.configure.outputs.suffix}} \
        --header "authorization: Bearer ${{ github.token }}" \
        --output "${{steps.configure.outputs.working_path}}/spaces.${{steps.configure.outputs.suffix}}" \
        --location --silent --show-error --fail --retry 5
      shell: bash

    - run: unzip "${{steps.configure.outputs.working_path}}/spaces.${{steps.configure.outputs.suffix}}" -C "${{steps.configure.outputs.working_path}}/bin"
      if: ${{runner.os != 'Windows'}}
      shell: bash

    - run: unzip "${{steps.configure.outputs.working_path}}/spaces.${{steps.configure.outputs.suffix}}" -O >"${{steps.configure.outputs.working_path}}/bin/spaces.exe" --force-local
      if: ${{runner.os == 'Windows'}}
      shell: bash

    - run: echo "${{steps.configure.outputs.working_path}}/bin" >> $GITHUB_PATH
      shell: bash

    - run: spaces --version
      shell: bash