name: install spaces
author: Tyler Gilbert
description: Prebuilt binaries of https://github.com/work-spaces/spaces
branding:
  icon: activity
  color: purple

runs:
  using: composite
  steps:
    - id: configure
      run: |
        echo platform=${{runner.os == 'macOS' && 'macos-x86_64' || runner.os == 'Windows' && 'windows-x86_64' || 'linux-x86_64'}} >> $GITHUB_OUTPUT
        echo version=v0.8.13 >> $GITHUB_OUTPUT
      shell: bash

    - run: mkdir -p "${{runner.temp}}/install-spaces/bin"
      shell: bash

    - run: |
        curl https://github.com/work-spaces/spaces/releases/download/${{steps.configure.outputs.version}}/spaces-${{steps.configure.outputs.platform}}-${{steps.configure.outputs.version}}.zip \
        --header "authorization: Bearer ${{ github.token }}" \
        --location --silent --show-error --fail --retry 5 > "${{runner.temp}}/install-spaces/spaces.zip"
      shell: bash

    - run: unzip "${{runner.temp}}/install-spaces/spaces.zip" -d "${{runner.temp}}/install-spaces/bin"
      shell: bash

    - run: echo "${{runner.temp}}/install-spaces/bin" >> $GITHUB_PATH
      shell: bash

    - run: spaces --version
      shell: bash
