name: CI

on:
  push:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

jobs:
  install:
    name: Install spaces
    timeout-minutes: 45
    strategy:
        matrix:
            os:
                - windows-latest
                - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: test that spaces is not preinstalled
        run: |
          if spaces --version; then which spaces; exit 1; fi
        shell: bash
      - name: install spaces
        uses: ./
      - run: spaces --version